### PR TITLE
Added bought list view

### PR DESCRIPTION
**Pull request by UnluckyBird**
Added bought list view and added needed gun functionality to list class

### CODE REVIEW

**Comment by mikejensen0** [comment]
image
Numbers have no 'kr.' after them, and perhaps make the numbers bigger and move them to the right, as seen on Figma:
image

**Review by mikejensen0 — CHANGES_REQUESTED** [review]
.

**Review by mikejensen0 — CHANGES_REQUESTED** [review]
.

**Review by mikejensen0 — COMMENTED** [review]
LGTM, but maybe have a way to delete items marked as bought by mistake.

**Review by andreasalstrup — APPROVED** [review]
LGTM

**Pull request merged**
