### PR TITLE
Notice Board and QR codes

### PR DESCRIPTION
**Pull request by UnluckyBird**
DO NOT USE DEFAULT 12345678 USER(I broke him)

Hooked up notice board to GunDB
Show QR code in notice board
Allow for QR code scanning when joining group

For testing you can use the users 44444444 or 66666666 or create new ones
Can be test using the QR code
386845463_865989015307943_5799791996546069278_n

### CODE REVIEW

**Comment by andreasalstrup** [comment]
Okay HUGE!

**Review by andreasalstrup — APPROVED** [review]
Tested with multiple new users and it just works!

**Comment by andreasalstrup** [comment]
Mindre bug efter cold boot: `Contact Information` bliver kun vist for bruger der logger ind.
`Contact Information` bliver vist normalt efter logout og login igen.

**Comment by UnluckyBird** [comment]
> Mindre bug efter cold boot: `Contact Information` bliver kun vist for bruger der logger ind. `Contact Information` bliver vist normalt efter logout og login igen.

Has been Fixed

**Comment by andreasalstrup** [comment]
Clicking `Expenses` gives: 
` ERROR  TypeError: callback is not a function (it is 'd70da490-bf0c-4a69-b6ad-6f969834305e'), js engine: hermes`

**Comment by andreasalstrup** [comment]
New QR

**Comment by UnluckyBird** [comment]
> Clicking `Expenses` gives: ` ERROR TypeError: callback is not a function (it is 'd70da490-bf0c-4a69-b6ad-6f969834305e'), js engine: hermes`

Woops my bad, is fixed

**Comment by andreasalstrup** [comment]
Funny bug when editing mid sentence in the rules section.


(not a breaking bug)

**Comment by andreasalstrup** [comment]
Looks very good to me!

**Comment by emilnormann** [comment]
Screenshot_2023-12-17-15-47-38-98_f73b71075b1de7323614b647fe394240
Med langt gruppenavn er qr basically offscreen og meget svær at trykke på.

**Comment by andreasalstrup** [comment]
Få en telefon med bedre opløsning Emil

**Comment by emilnormann** [comment]
Knappen 'Join by group id' kunne måske også omdøbes til at inkludere qr

**Comment by UnluckyBird** [comment]
> Knappen 'Join by group id' kunne måske også omdøbes til at inkludere qr

Ehh disagree, the QR code is still just a groupId, and will not show if you haven't given the app permission to use camera

**Comment by UnluckyBird** [comment]
> Med langt gruppenavn er qr basically offscreen og meget svær at trykke på.

Have changed Group ID to ID to make more space, and made text otherwise wrap instead of going off screen

**Review by emilnormann — APPROVED** [review]

**Pull request merged**
